version: "3"
services:
  ecommerce-ui:
    image:  vanuhanda/ecommerce-ui
    container_name: ecommerce-ui
    ports:
      - "4000:4000"
    environment:
      - REACT_APP_PROFILE_API_HOST=http://profile-management
      - REACT_APP_PRODUCT_API_HOST=http://product-catalog
      - REACT_APP_INVENTORY_API_HOST=http://product-inventory
      - REACT_APP_ORDER_API_HOST=http://order-management
      - REACT_APP_SHIPPING_API_HOST=http://shipping-and-handling
      - REACT_APP_CONTACT_API_HOST=http://contact-support-team
    depends_on:
      - profile-management
      - product-catalog
      - product-inventory
      - order-management
      - shipping-and-handling
      - contact-support-team
  contact-support-team:
    image: vanuhanda/contact-support-team:2.0.0
    container_name: contact-support-team
    ports:
      - "8000:8000"
    depends_on:
      - mongodb-contact-support
    environment:
      - MONGODB_HOST=mongodb-contact-support
      - MONGODB_PORT=27017
      - MONGODB_DATABASE=contact_support

  mongodb-contact-support: ## mongodb will use container port 27017
    image: mongo
    container_name: mongodb-contact-support
    volumes:
      - mongodb_contact_support_data:/data/db
  shipping-and-handling:
    image: vanuhanda/shipping-and-handling:2.0.0
    container_name: shipping-and-handling
    ports:
      - "8080:8080"
    depends_on:
      - mongodb-shipping
    environment:
      - MONGO_URI=mongodb://mongodb-shipping:27017

  mongodb-shipping: ## mongodb will use container port 27017
    image: mongo
    container_name: mongodb-shipping
    ports:
      - "27020:27017"
    volumes:
      - mongodb_shipping_data:/data/db
  product-catalog:
    image: vanuhanda/product-catalog:2.0.0
    container_name: product-catalog
    ports:
      - "3001:3001"
    depends_on:
      - mongodb-product-catalog
    environment:
      - MONGODB_HOST=mongodb-product-catalog
      - MONGODB_PORT=27017
      - MONGODB_DATABASE=product_catalog
  mongodb-product-catalog: ## mongodb will use container port 27017
    image: mongo
    container_name: mongodb-product-catalog
    volumes:
      - mongodb_product_catalog_data:/data/db
  order-management:
    image: vanuhanda/order-management:2.0.0
    container_name: order-management
    depends_on:
      - mongodb-order-management
    ports:
      - "9090:9090"
    environment:
      - PRODUCT_INVENTORY_API_HOST=http://product-inventory
      - PRODUCT_CATALOG_API_HOST=http://product-catalog
      - SHIPPING_HANDLING_API_HOST=http://shipping-and-handling
      - SPRING_DATA_MONGODB_URI=mongodb://mongodb-order-management:27017/order_management
  mongodb-order-management: ## mongodb will use container 27017
    image: mongo
    container_name: mongodb-order-management
    ports:
      - "27021:27017"
    volumes:
      - mongodb_order_management_data:/data/db
  product-inventory:
    image: vanuhanda/product-inventory:2.0.0
    container_name: product-inventory
    depends_on:
      - postgres_product_inventory
    ports:
      - "3002:3002"
    environment:
      - POSTGRES_HOST=postgres_product_inventory
      - POSTGRES_PORT=5432
      - POSTGRES_DB=product_inventory
      - POSTGRES_USER=inventory_user
      - POSTGRES_PASSWORD=inventory_password
  postgres_product_inventory: ## postgres will run on container port 5432
    image: postgres
    container_name: postgres_product_inventory
    environment:
      - POSTGRES_DB=product_inventory
      - POSTGRES_USER=inventory_user
      - POSTGRES_PASSWORD=inventory_password
    volumes:
      - postgres_product_inventory_data:/var/lib/postgresql
  profile-management:
    image: vanuhanda/profile-management:2.0.0
    container_name: profile-management
    ports:
      - "3003:3003"
    depends_on:
      - mysql_profile_management
    environment:
      - MYSQL_HOST=mysql_profile_management
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=profile_management
      - MYSQL_USER=profile_user
      - MYSQL_PASSWORD=profile_password
  mysql_profile_management: ## will run on container 3306
    image: mysql:8.0
    container_name: mysql_profile_management
    environment:
      - MYSQL_DATABASE=profile_management
      - MYSQL_USER=profile_user
      - MYSQL_PASSWORD=profile_password
      - MYSQL_ROOT_PASSWORD=root_password
    volumes:
      - mysql_profile_management_data:/var/lib/mysql

volumes:
  mongodb_product_catalog_data:
  mongodb_contact_support_data:
  mongodb_shipping_data:
  mongodb_order_management_data:
  mysql_profile_management_data:
  postgres_product_inventory_data: